name: carrot_market_turtorial
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  carousel_slider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/

  fonts:
    - family: NotoSansCJKkr
      fonts:
        - asset: assets/fonts/NotoSansCJKkr-Black.otf
        - asset: assets/fonts/NotoSansCJKkr-Bold.otf
        - asset: assets/fonts/NotoSansCJKkr-Medium.otf
        - asset: assets/fonts/NotoSansCJKkr-Regular.otf
        - asset: assets/fonts/NotoSansCJKkr-DemiLight.otf
        - asset: assets/fonts/NotoSansCJKkr-Light.otf
        - asset: assets/fonts/NotoSansCJKkr-Thin.otf

